#######################################################################
# Setup
#######################################################################

enable_testing()

function( add_cpp_test name source )

  set( test_name "ACEtk.${name}.test" )
  add_executable( ${test_name} ${source} )
  add_test( NAME ${test_name} COMMAND ${test_name} )
  target_link_libraries( ${test_name} PRIVATE ACEtk )
  target_link_libraries( ${test_name} PRIVATE Catch2::Catch2WithMain )

  file( GLOB resources "resources/*" )
  foreach( resource ${resources} )
    file( COPY "${resource}" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}" )
  endforeach()

endfunction()

#######################################################################
# Unit testing directories
#######################################################################

message( STATUS "Adding ACEtk C++ unit testing" )

add_cpp_test( ContinuousEnergyTable ContinuousEnergyTable.test.cpp )
add_cpp_test( DosimetryTable DosimetryTable.test.cpp )
add_cpp_test( ElectronTable ElectronTable.test.cpp )
add_cpp_test( PhotoatomicTable PhotoatomicTable.test.cpp )
add_cpp_test( PhotonuclearTable PhotonuclearTable.test.cpp )
add_cpp_test( Table.Data.Parse Table/Data/Parse.test.cpp )
add_cpp_test( Table.Data.Data Table/Data/Data.test.cpp )
add_cpp_test( Table.Header Table/Header.test.cpp )
add_cpp_test( Table.Header201 Table/Header201.test.cpp )
add_cpp_test( Table.Table Table/Table.test.cpp )
add_cpp_test( ThermalScatteringTable ThermalScatteringTable.test.cpp )
add_cpp_test( Xsdir Xsdir.test.cpp )
add_cpp_test( XsdirEntry XsdirEntry.test.cpp )
add_cpp_test( continuous.AngleEnergyDistributionData continuous/AngleEnergyDistributionData.test.cpp )
add_cpp_test( continuous.AngularDistributionBlock continuous/AngularDistributionBlock.test.cpp )
add_cpp_test( continuous.AngularDistributionData continuous/AngularDistributionData.test.cpp )
add_cpp_test( continuous.CrossSectionBlock continuous/CrossSectionBlock.test.cpp )
add_cpp_test( continuous.CrossSectionData continuous/CrossSectionData.test.cpp )
add_cpp_test( continuous.DelayedNeutronPrecursorBlock continuous/DelayedNeutronPrecursorBlock.test.cpp )
add_cpp_test( continuous.DelayedNeutronPrecursorData continuous/DelayedNeutronPrecursorData.test.cpp )
add_cpp_test( continuous.DiscretePhotonDistribution continuous/DiscretePhotonDistribution.test.cpp )
add_cpp_test( continuous.DistributionProbability continuous/DistributionProbability.test.cpp )
add_cpp_test( continuous.EnergyAngleDistributionData continuous/EnergyAngleDistributionData.test.cpp )
add_cpp_test( continuous.EnergyDependentWattSpectrum continuous/EnergyDependentWattSpectrum.test.cpp )
add_cpp_test( continuous.EnergyDistributionBlock continuous/EnergyDistributionBlock.test.cpp )
add_cpp_test( continuous.EquiprobableAngularBins continuous/EquiprobableAngularBins.test.cpp )
add_cpp_test( continuous.EquiprobableOutgoingEnergyBinData continuous/EquiprobableOutgoingEnergyBinData.test.cpp )
add_cpp_test( continuous.EquiprobableOutgoingEnergyBins continuous/EquiprobableOutgoingEnergyBins.test.cpp )
add_cpp_test( continuous.EvaporationSpectrum continuous/EvaporationSpectrum.test.cpp )
add_cpp_test( continuous.FissionMultiplicityBlock continuous/FissionMultiplicityBlock.test.cpp )
add_cpp_test( continuous.FrameAndMultiplicityBlock continuous/FrameAndMultiplicityBlock.test.cpp )
add_cpp_test( continuous.GeneralEvaporationSpectrum continuous/GeneralEvaporationSpectrum.test.cpp )
add_cpp_test( continuous.InterpolationData continuous/InterpolationData.test.cpp )
add_cpp_test( continuous.IsotropicAngularDistribution continuous/IsotropicAngularDistribution.test.cpp )
add_cpp_test( continuous.KalbachMannDistributionData continuous/KalbachMannDistributionData.test.cpp )
add_cpp_test( continuous.LevelScatteringDistribution continuous/LevelScatteringDistribution.test.cpp )
add_cpp_test( continuous.MultiDistributionData continuous/MultiDistributionData.test.cpp )
add_cpp_test( continuous.MultiplicityReactionNumberBlock continuous/MultiplicityReactionNumberBlock.test.cpp )
add_cpp_test( continuous.NBodyPhaseSpaceDistribution continuous/NBodyPhaseSpaceDistribution.test.cpp )
add_cpp_test( continuous.OutgoingEnergyDistributionData continuous/OutgoingEnergyDistributionData.test.cpp )
add_cpp_test( continuous.ParameterData continuous/ParameterData.test.cpp )
add_cpp_test( continuous.PhotonProductionBlock continuous/PhotonProductionBlock.test.cpp )
add_cpp_test( continuous.PhotonProductionCrossSectionBlock continuous/PhotonProductionCrossSectionBlock.test.cpp )
add_cpp_test( continuous.PhotonProductionCrossSectionData continuous/PhotonProductionCrossSectionData.test.cpp )
add_cpp_test( continuous.PolynomialFissionMultiplicity continuous/PolynomialFissionMultiplicity.test.cpp )
add_cpp_test( continuous.PrincipalCrossSectionBlock continuous/PrincipalCrossSectionBlock.test.cpp )
add_cpp_test( continuous.ProbabilityTable continuous/ProbabilityTable.test.cpp )
add_cpp_test( continuous.ProbabilityTableBlock continuous/ProbabilityTableBlock.test.cpp )
add_cpp_test( continuous.ReactionNumberBlock continuous/ReactionNumberBlock.test.cpp )
add_cpp_test( continuous.ReactionQValueBlock continuous/ReactionQValueBlock.test.cpp )
add_cpp_test( continuous.SecondaryParticleAngularDistributionBlock continuous/SecondaryParticleAngularDistributionBlock.test.cpp )
add_cpp_test( continuous.SecondaryParticleEnergyDistributionBlock continuous/SecondaryParticleEnergyDistributionBlock.test.cpp )
add_cpp_test( continuous.SecondaryParticleInformationBlock continuous/SecondaryParticleInformationBlock.test.cpp )
add_cpp_test( continuous.SecondaryParticleLocatorBlock continuous/SecondaryParticleLocatorBlock.test.cpp )
add_cpp_test( continuous.SecondaryParticleProductionBlock continuous/SecondaryParticleProductionBlock.test.cpp )
add_cpp_test( continuous.TabulatedMultiplicity continuous/TabulatedMultiplicity.test.cpp )
add_cpp_test( continuous.SecondaryParticleProductionCrossSectionBlock continuous/SecondaryParticleProductionCrossSectionBlock.test.cpp )
add_cpp_test( continuous.SecondaryParticleTypeBlock continuous/SecondaryParticleTypeBlock.test.cpp )
add_cpp_test( continuous.SimpleMaxwellianFissionSpectrum continuous/SimpleMaxwellianFissionSpectrum.test.cpp )
add_cpp_test( continuous.TabulatedAngleEnergyDistribution continuous/TabulatedAngleEnergyDistribution.test.cpp )
add_cpp_test( continuous.TabulatedAngularDistribution continuous/TabulatedAngularDistribution.test.cpp )
add_cpp_test( continuous.TabulatedAngularDistributionWithProbability continuous/TabulatedAngularDistributionWithProbability.test.cpp )
add_cpp_test( continuous.TabulatedEnergyAngleDistribution continuous/TabulatedEnergyAngleDistribution.test.cpp )
add_cpp_test( continuous.TabulatedEnergyDistribution continuous/TabulatedEnergyDistribution.test.cpp )
add_cpp_test( continuous.TabulatedFissionMultiplicity continuous/TabulatedFissionMultiplicity.test.cpp )
add_cpp_test( continuous.TabulatedKalbachMannDistribution continuous/TabulatedKalbachMannDistribution.test.cpp )
add_cpp_test( continuous.TabulatedSecondaryParticleMultiplicity continuous/TabulatedSecondaryParticleMultiplicity.test.cpp )
add_cpp_test( continuous.TwoBodyTransferDistribution continuous/TwoBodyTransferDistribution.test.cpp )
add_cpp_test( dosimetry.CrossSectionBlock dosimetry/CrossSectionBlock.test.cpp )
add_cpp_test( dosimetry.CrossSectionData dosimetry/CrossSectionData.test.cpp )
add_cpp_test( electroatomic.BremsstrahlungBlock electroatomic/BremsstrahlungBlock.test.cpp )
add_cpp_test( electroatomic.ElasticAngularDistributionBlock electroatomic/ElasticAngularDistributionBlock.test.cpp )
add_cpp_test( electroatomic.ElasticCrossSectionBlock electroatomic/ElasticCrossSectionBlock.test.cpp )
add_cpp_test( electroatomic.ElectronShellBlock electroatomic/ElectronShellBlock.test.cpp )
add_cpp_test( electroatomic.ElectronSubshellBlock electroatomic/ElectronSubshellBlock.test.cpp )
add_cpp_test( electroatomic.EnergyDistributionBlock electroatomic/EnergyDistributionBlock.test.cpp )
add_cpp_test( electroatomic.ExcitationBlock electroatomic/ExcitationBlock.test.cpp )
add_cpp_test( electroatomic.PrincipalCrossSectionBlock electroatomic/PrincipalCrossSectionBlock.test.cpp )
add_cpp_test( electroatomic.SubshellTransitionData electroatomic/SubshellTransitionData.test.cpp )
add_cpp_test( electroatomic.SubshellTransitionDataBlock electroatomic/SubshellTransitionDataBlock.test.cpp )
add_cpp_test( electroatomic.TabulatedAngularDistribution electroatomic/TabulatedAngularDistribution.test.cpp )
add_cpp_test( electroatomic.TabulatedEnergyDistribution electroatomic/TabulatedEnergyDistribution.test.cpp )
add_cpp_test( electron.BremsstrahlungAngularSpectrumBlock electron/BremsstrahlungAngularSpectrumBlock.test.cpp )
add_cpp_test( electron.BremsstrahlungCorrectionFactorBlock electron/BremsstrahlungCorrectionFactorBlock.test.cpp )
add_cpp_test( electron.BremsstrahlungEnergySpectrumBlock electron/BremsstrahlungEnergySpectrumBlock.test.cpp )
add_cpp_test( electron.BremsstrahlungHighFrequencyBlock electron/BremsstrahlungHighFrequencyBlock.test.cpp )
add_cpp_test( electron.BremsstrahlungProductionBlock electron/BremsstrahlungProductionBlock.test.cpp )
add_cpp_test( electron.MottScatteringCorrectionBlock electron/MottScatteringCorrectionBlock.test.cpp )
add_cpp_test( electron.OscillatorBlock electron/OscillatorBlock.test.cpp )
add_cpp_test( electron.RadiationStoppingPowerBlock electron/RadiationStoppingPowerBlock.test.cpp )
add_cpp_test( electron.RileyCrossSectionBlock electron/RileyCrossSectionBlock.test.cpp )
add_cpp_test( electron.TransitionEnergyBlock electron/TransitionEnergyBlock.test.cpp )
add_cpp_test( photoatomic.CoherentFormFactorBlock photoatomic/CoherentFormFactorBlock.test.cpp )
add_cpp_test( photoatomic.ComptonProfile photoatomic/ComptonProfile.test.cpp )
add_cpp_test( photoatomic.ComptonProfileBlock photoatomic/ComptonProfileBlock.test.cpp )
add_cpp_test( photoatomic.FluorescenceDataBlock photoatomic/FluorescenceDataBlock.test.cpp )
add_cpp_test( photoatomic.HeatingNumbersBlock photoatomic/HeatingNumbersBlock.test.cpp )
add_cpp_test( photoatomic.IncoherentScatteringFunctionBlock photoatomic/IncoherentScatteringFunctionBlock.test.cpp )
add_cpp_test( photoatomic.PhotoelectricCrossSectionBlock photoatomic/PhotoelectricCrossSectionBlock.test.cpp )
add_cpp_test( photoatomic.PrincipalCrossSectionBlock photoatomic/PrincipalCrossSectionBlock.test.cpp )
add_cpp_test( photonuclear.PrincipalCrossSectionBlock photonuclear/PrincipalCrossSectionBlock.test.cpp )
add_cpp_test( photonuclear.SecondaryParticleLocatorBlock photonuclear/SecondaryParticleLocatorBlock.test.cpp )
add_cpp_test( thermal.CrossSectionBlock thermal/CrossSectionBlock.test.cpp )
add_cpp_test( thermal.DiscreteCosines thermal/DiscreteCosines.test.cpp )
add_cpp_test( thermal.DiscreteCosinesWithProbability thermal/DiscreteCosinesWithProbability.test.cpp )
add_cpp_test( thermal.ElasticAngularDistributionBlock thermal/ElasticAngularDistributionBlock.test.cpp )
add_cpp_test( thermal.InelasticAngularDistributionBlock thermal/InelasticAngularDistributionBlock.test.cpp )
