#######################################################################
# Setup
#######################################################################

enable_testing()

function( add_python_test name source )

  set( test_name "ACEtk.python.${name}.test" )
  add_test( NAME ${test_name}
            COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/${source}
            WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
  set_tests_properties( ${test_name}
                        PROPERTIES ENVIRONMENT
                        PYTHONPATH=${ACEtk_PYTHONPATH}:$ENV{PYTHONPATH})

endfunction()

#######################################################################
# Python unit testing
#######################################################################

message( STATUS "Adding ACEtk Python unit testing" )

add_python_test( continuous.TwoBodyTransferDistribution                  continuous/Test_ACEtk_continuous_TwoBodyTransferDistribution )
add_python_test( continuous.TabulatedSecondaryParticleMultiplicity       continuous/Test_ACEtk_continuous_TabulatedSecondaryParticleMultiplicity )
add_python_test( continuous.TabulatedMultiplicity                        continuous/Test_ACEtk_continuous_TabulatedMultiplicity )
add_python_test( continuous.TabulatedKalbachMannDistribution             continuous/Test_ACEtk_continuous_TabulatedKalbachMannDistribution )
add_python_test( continuous.TabulatedFissionMultiplicity                 continuous/Test_ACEtk_continuous_TabulatedFissionMultiplicity )
add_python_test( continuous.TabulatedEnergyDistribution                  continuous/Test_ACEtk_continuous_TabulatedEnergyDistribution )
add_python_test( continuous.TabulatedEnergyAngleDistribution             continuous/Test_ACEtk_continuous_TabulatedEnergyAngleDistribution )
add_python_test( continuous.TabulatedAngularDistributionWithProbability  continuous/Test_ACEtk_continuous_TabulatedAngularDistributionWithProbability )
add_python_test( continuous.TabulatedAngularDistribution                 continuous/Test_ACEtk_continuous_TabulatedAngularDistribution )
add_python_test( continuous.TabulatedAngleEnergyDistribution             continuous/Test_ACEtk_continuous_TabulatedAngleEnergyDistribution )
add_python_test( continuous.SimpleMaxwellianFissionSpectrum              continuous/Test_ACEtk_continuous_SimpleMaxwellianFissionSpectrum )
add_python_test( continuous.SecondaryParticleTypeBlock                   continuous/Test_ACEtk_continuous_SecondaryParticleTypeBlock )
add_python_test( continuous.SecondaryParticleProductionCrossSectionBlock continuous/Test_ACEtk_continuous_SecondaryParticleProductionCrossSectionBlock )
add_python_test( continuous.SecondaryParticleProductionBlock             continuous/Test_ACEtk_continuous_SecondaryParticleProductionBlock )
add_python_test( continuous.SecondaryParticleLocatorBlock                continuous/Test_ACEtk_continuous_SecondaryParticleLocatorBlock )
add_python_test( continuous.SecondaryParticleInformationBlock            continuous/Test_ACEtk_continuous_SecondaryParticleInformationBlock )
add_python_test( continuous.SecondaryParticleEnergyDistributionBlock     continuous/Test_ACEtk_continuous_SecondaryParticleEnergyDistributionBlock )
add_python_test( continuous.SecondaryParticleAngularDistributionBlock    continuous/Test_ACEtk_continuous_SecondaryParticleAngularDistributionBlock )
add_python_test( continuous.ReactionQValueBlock                          continuous/Test_ACEtk_continuous_ReactionQValueBlock )
add_python_test( continuous.ReactionNumberBlock                          continuous/Test_ACEtk_continuous_ReactionNumberBlock )
add_python_test( continuous.ProbabilityTableBlock                        continuous/Test_ACEtk_continuous_ProbabilityTableBlock )
add_python_test( continuous.ProbabilityTable                             continuous/Test_ACEtk_continuous_ProbabilityTable )
add_python_test( continuous.PrincipalCrossSectionBlock                   continuous/Test_ACEtk_continuous_PrincipalCrossSectionBlock )
add_python_test( continuous.PolynomialFissionMultiplicity                continuous/Test_ACEtk_continuous_PolynomialFissionMultiplicity )
add_python_test( continuous.PhotonProductionCrossSectionData             continuous/Test_ACEtk_continuous_PhotonProductionCrossSectionData )
add_python_test( continuous.PhotonProductionCrossSectionBlock            continuous/Test_ACEtk_continuous_PhotonProductionCrossSectionBlock )
add_python_test( continuous.PhotonProductionBlock                        continuous/Test_ACEtk_continuous_PhotonProductionBlock )
add_python_test( continuous.ParameterData                                continuous/Test_ACEtk_continuous_ParameterData )
add_python_test( continuous.OutgoingEnergyDistributionData               continuous/Test_ACEtk_continuous_OutgoingEnergyDistributionData )
add_python_test( continuous.NBodyPhaseSpaceDistribution                  continuous/Test_ACEtk_continuous_NBodyPhaseSpaceDistribution )
add_python_test( continuous.MultiplicityReactionNumberBlock              continuous/Test_ACEtk_continuous_MultiplicityReactionNumberBlock )
add_python_test( continuous.MultiDistributionData                        continuous/Test_ACEtk_continuous_MultiDistributionData )
add_python_test( continuous.LevelScatteringDistribution                  continuous/Test_ACEtk_continuous_LevelScatteringDistribution )
add_python_test( continuous.KalbachMannDistributionData                  continuous/Test_ACEtk_continuous_KalbachMannDistributionData )
add_python_test( continuous.IsotropicAngularDistribution                 continuous/Test_ACEtk_continuous_IsotropicAngularDistribution )
add_python_test( continuous.InterpolationData                            continuous/Test_ACEtk_continuous_InterpolationData )
add_python_test( continuous.GeneralEvaporationSpectrum                   continuous/Test_ACEtk_continuous_GeneralEvaporationSpectrum )
add_python_test( continuous.FullyIsotropicDistribution                   continuous/Test_ACEtk_continuous_FullyIsotropicDistribution )
add_python_test( continuous.FrameAndMultiplicityBlock                    continuous/Test_ACEtk_continuous_FrameAndMultiplicityBlock )
add_python_test( continuous.FissionMultiplicityBlock                     continuous/Test_ACEtk_continuous_FissionMultiplicityBlock )
add_python_test( continuous.EvaporationSpectrum                          continuous/Test_ACEtk_continuous_EvaporationSpectrum )
add_python_test( continuous.EquiprobableOutgoingEnergyBins               continuous/Test_ACEtk_continuous_EquiprobableOutgoingEnergyBins )
add_python_test( continuous.EquiprobableOutgoingEnergyBinData            continuous/Test_ACEtk_continuous_EquiprobableOutgoingEnergyBinData )
add_python_test( continuous.EquiprobableAngularBins                      continuous/Test_ACEtk_continuous_EquiprobableAngularBins )
add_python_test( continuous.EnergyDistributionBlock                      continuous/Test_ACEtk_continuous_EnergyDistributionBlock )
add_python_test( continuous.EnergyDependentWattSpectrum                  continuous/Test_ACEtk_continuous_EnergyDependentWattSpectrum )
add_python_test( continuous.EnergyAngleDistributionData                  continuous/Test_ACEtk_continuous_EnergyAngleDistributionData )
add_python_test( continuous.DistributionProbability                      continuous/Test_ACEtk_continuous_DistributionProbability )
add_python_test( continuous.DistributionGivenElsewhere                   continuous/Test_ACEtk_continuous_DistributionGivenElsewhere )
add_python_test( continuous.DiscretePhotonDistribution                   continuous/Test_ACEtk_continuous_DiscretePhotonDistribution )
add_python_test( continuous.DelayedNeutronPrecursorData                  continuous/Test_ACEtk_continuous_DelayedNeutronPrecursorData )
add_python_test( continuous.DelayedNeutronPrecursorBlock                 continuous/Test_ACEtk_continuous_DelayedNeutronPrecursorBlock )
add_python_test( continuous.CrossSectionData                             continuous/Test_ACEtk_continuous_CrossSectionData )
add_python_test( continuous.CrossSectionBlock                            continuous/Test_ACEtk_continuous_CrossSectionBlock )
add_python_test( continuous.AngularDistributionData                      continuous/Test_ACEtk_continuous_AngularDistributionData )
add_python_test( continuous.AngularDistributionBlock                     continuous/Test_ACEtk_continuous_AngularDistributionBlock )
add_python_test( continuous.AngleEnergyDistributionData                  continuous/Test_ACEtk_continuous_AngleEnergyDistributionData )

add_python_test( photonuclear.PrincipalCrossSectionBlock    photonuclear/Test_ACEtk_photonuclear_PrincipalCrossSectionBlock.py )
add_python_test( photonuclear.SecondaryParticleLocatorBlock photonuclear/Test_ACEtk_photonuclear_SecondaryParticleLocatorBlock.py )

add_python_test( photoatomic.PrincipalCrossSectionBlock        photoatomic/Test_ACEtk_photoatomic_PrincipalCrossSectionBlock.py )
add_python_test( photoatomic.IncoherentScatteringFunctionBlock photoatomic/Test_ACEtk_photoatomic_IncoherentScatteringFunctionBlock.py )
add_python_test( photoatomic.CoherentFormFactorBlock           photoatomic/Test_ACEtk_photoatomic_CoherentFormFactorBlock.py )
add_python_test( photoatomic.FluorescenceDataBlock             photoatomic/Test_ACEtk_photoatomic_FluorescenceDataBlock.py )
add_python_test( photoatomic.HeatingNumbersBlock               photoatomic/Test_ACEtk_photoatomic_HeatingNumbersBlock.py )
add_python_test( photoatomic.ComptonProfile                    photoatomic/Test_ACEtk_photoatomic_ComptonProfile.py )
add_python_test( photoatomic.ComptonProfileBlock               photoatomic/Test_ACEtk_photoatomic_ComptonProfileBlock.py )
add_python_test( photoatomic.PhotoelectricCrossSectionBlock    photoatomic/Test_ACEtk_photoatomic_PhotoelectricCrossSectionBlock.py )

add_python_test( dosimetry.CrossSectionBlock dosimetry/Test_ACEtk_dosimetry_CrossSectionBlock.py )
add_python_test( dosimetry.CrossSectionData  dosimetry/Test_ACEtk_dosimetry_CrossSectionData.py )

add_python_test( electron.ElectronShellBlock              electron/Test_ACEtk_electron_ElectronShellBlock.py )
add_python_test( electron.ElectronSubshellBlock           electron/Test_ACEtk_electron_ElectronSubshellBlock.py )
add_python_test( electron.PrincipalCrossSectionBlock      electron/Test_ACEtk_electron_PrincipalCrossSectionBlock.py )
add_python_test( electron.ElasticCrossSectionBlock        electron/Test_ACEtk_electron_ElasticCrossSectionBlock.py )
add_python_test( electron.ExcitationBlock                 electron/Test_ACEtk_electron_ExcitationBlock.py )
add_python_test( electron.BremsstrahlungBlock             electron/Test_ACEtk_electron_BremsstrahlungBlock.py )
add_python_test( electron.SubshellTransitionData          electron/Test_ACEtk_electron_SubshellTransitionData.py )
add_python_test( electron.SubshellTransitionDataBlock     electron/Test_ACEtk_electron_SubshellTransitionDataBlock.py )
add_python_test( electron.TabulatedAngularDistribution    electron/Test_ACEtk_electron_TabulatedAngularDistribution.py )
add_python_test( electron.TabulatedEnergyDistribution     electron/Test_ACEtk_electron_TabulatedEnergyDistribution.py )
add_python_test( electron.ElasticAngularDistributionBlock electron/Test_ACEtk_electron_ElasticAngularDistributionBlock.py )
add_python_test( electron.EnergyDistributionBlock         electron/Test_ACEtk_electron_EnergyDistributionBlock.py )

add_python_test( thermal.CrossSectionBlock                 thermal/Test_ACEtk_thermal_CrossSectionBlock.py )
add_python_test( thermal.DiscreteCosines                   thermal/Test_ACEtk_thermal_DiscreteCosines.py )
add_python_test( thermal.DiscreteCosinesWithProbability    thermal/Test_ACEtk_thermal_DiscreteCosinesWithProbability.py )
add_python_test( thermal.ElasticAngularDistributionBlock   thermal/Test_ACEtk_thermal_ElasticAngularDistributionBlock.py )
add_python_test( thermal.InelasticAngularDistributionBlock thermal/Test_ACEtk_thermal_InelasticAngularDistributionBlock.py )
