/**
 *  @class
 *  @brief The header information in an ACE file
 *
 *  There are multiple version of the header. This is the modernised header
 *  (version 2.0.0 or 2.0.1) used for the official ENDF/B-VII.1 and ENDF/B-VIII.0
 *  ACE libraries. This header is not generated by NJOY
 *
 *  The 2.0.0 header contains the following information, in free format:
 *    - line 1: VERS (header version, 10 characters), blank space,
 *              SZAID (24 characters), blank space,
 *              SRC (evaluation source, 24 characters)
 *    - line 2: AW (atomic mass ratio), TZ (temperature in MeV), date,
 *              N (comments)
 *    - line 3 to N+2: comment lines (the last two lines are always the normal
 *                     header)
 *
 *  The 2.0.1 header contains the following information, fixed column format:
 *    - line 1: VERS (header version, 10 characters), blank space,
 *              SZAID (24 characters), blank space,
 *              SRC (evaluation source, 24 characters)
 *    - line 2: AW (atomic mass ratio, 12 characters), blank space,
 *              TZ (temperature in MeV, 12 characters), blank space,
 *              date (10 characters), blank space, N (number of comment lines,
 *              4 characters)
 *    - line 3 to N+2: comment lines (the last two lines are always the normal
 *                     header)
 */
class Header201 {

  /* fields */
  std::string vers_;
  std::string szaid_;
  std::string src_;
  double temp_;
  double awr_;
  std::string date_;
  std::vector< std::string > comments_;

  /* auxiliary functions */
  #include "ACEtk/Table/Header/src/strip.hpp"
  #include "ACEtk/Table/Header201/src/parse.hpp"

public:

  #include "ACEtk/Table/Header201/src/ctor.hpp"

  /**
   *  @brief Return the header version
   */
  const std::string& VERS() const { return this->vers_; }

  /**
   *  @brief Return the header version
   */
  const std::string& version() const { return this->VERS(); }

  /**
   *  @brief Return the full ZAID or SZAID of the table
   */
  const std::string& ZAID() const { return this->szaid_; }

  /**
   *  @brief Return the source of the table
   */
  const std::string& SRC() const { return this->src_; }

  /**
   *  @brief Return the source of the table
   */
  const std::string& source() const { return this->SRC(); }

  /**
   *  @brief Return the atomic weight ratio (with respect to the neutron mass)
   */
  double AWR() const { return this->awr_; }

  /**
   *  @brief Return the atomic weight ratio (with respect to the neutron mass)
   */
  double atomicWeightRatio() const { return this->AWR(); }

  /**
   *  @brief Return the temperature of the table
   */
  double TEMP() const { return this->temp_; }

  /**
   *  @brief Return the temperature of the table
   */
  double temperature() const { return this->TEMP(); }

  /**
   *  @brief Return the date
   */
  const std::string& date() const { return this->date_; }

  /**
   *  @brief Return the comments
   */
  const std::vector< std::string >& comments() const { return this->comments_; }

  #include "ACEtk/Table/Header201/src/print.hpp"
};
